// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MBAContext))]
    [Migration("20240403113449_SeedDataOfInformation")]
    partial class SeedDataOfInformation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Models.Entity.Describe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("Describe", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5534),
                            Description = "VỀ CÔNG TY",
                            Name = "Big Title",
                            SectionId = 3,
                            UpdatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5531)
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5536),
                            Description = "Tổng Giám đốc - Người sáng lập MBA",
                            Name = "General Manager",
                            SectionId = 3,
                            UpdatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5535)
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5539),
                            Description = "Let’s Grow Together!\r\nCùng đến thành công!",
                            Name = "Slogan",
                            SectionId = 3,
                            UpdatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5538)
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5541),
                            Description = "MBA International JSC",
                            Name = "Tag",
                            SectionId = 3,
                            UpdatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5540)
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5543),
                            Description = "CÔNG TY CỔ PHẦN QUỐC TẾ MBA",
                            Name = "Title",
                            SectionId = 3,
                            UpdatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5542)
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5545),
                            Description = "Công ty CP Quốc tế MBA là nhà sản xuất và phân phối hàng đầu các giải pháp toàn diện cho ngành Giáo Dục – Y Tế - Công Nghệ Cao. Với hơn 17 năm kinh nghiệm, MBA tự hào với đội ngũ nhân viên giàu kinh nghiệm, nhiệt huyết và chuyên nghiệp, luôn mang đến cho khách hàng những trải nghiệm tốt nhất về sản phẩm và dịch vụ chính hãng. Với  xu hướng phát triển không ngừng của ngành khoa học thông tin và cách mạng công nghiệp 4.0, nhằm đáp ứng nhu cầu ngày càng cao của khách hàng trong việc trang bị các thiết bị điện tử và các giải pháp công nghệ, Công Ty Cổ Phần Quốc Tế MBA đã mang đến cho Quý khách hàng những sản phẩm hiện đại nhất của các hãng nổi tiếng trên thị trường Bên cạnh đó ngoài chức năng phân phối, MBA cũng là đại diện bảo hành, bảo trì, sữa chữa và thực hiện các dịch vụ sau bán hàng của các đối tác nói trên nhằm cung cấp giải pháp toàn diện, hiệu quả cho khách hàng khi sử dụng sản phẩm MBA phân phối với đội kỹ thuật viên giàu kinh nghiệm, linh kiện thay thế chính hãng và giá cả hợp lý.",
                            Name = "Detail",
                            SectionId = 3,
                            UpdatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5544)
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5547),
                            Description = "TẦM NHÌN - SỨ MỆNH",
                            Name = "Big Title",
                            SectionId = 4,
                            UpdatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5546)
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5549),
                            Description = "Tầm nhìn thương hiệu",
                            Name = "Title",
                            SectionId = 4,
                            UpdatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5548)
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5551),
                            Description = "MBA International Corporation luôn hướng tới mục tiêu duy trì vị trí thương hiệu hàng đầu tại Việt Nam trong lĩnh vực phân phối các Thiết bị Giáo dục – Y tế – Công nghệ cao.",
                            Name = "Detail",
                            SectionId = 4,
                            UpdatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5550)
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5553),
                            Description = "Sứ mệnh",
                            Name = "Title2",
                            SectionId = 4,
                            UpdatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5552)
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5554),
                            Description = "Với tôn chỉ \" Let's Grow Together! - Cùng đến thành công !\", Công ty CP Quốc Tế MBA luôn hướng tới sự phát triển bền vững không chỉ cho doanh nghiệp mà còn cho cộng đồng bằng cam kết mang những sản phẩm ngành Giáo Dục - Y Tế - Công Nghệ Cao chất lượng hàng đầu Thế giới với giá cả cạnh tranh nhất đến đông đảo Quý khách hàng.",
                            Name = "Title2",
                            SectionId = 4,
                            UpdatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5553)
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5556),
                            Description = "LỊCH SỬ HÌNH THÀNH",
                            Name = "Big Title",
                            SectionId = 5,
                            UpdatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5555)
                        },
                        new
                        {
                            Id = 13,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5558),
                            Description = "BAN LÃNH ĐẠO",
                            Name = "Big Title",
                            SectionId = 6,
                            UpdatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5557)
                        });
                });

            modelBuilder.Entity("Core.Models.Entity.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("Image", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5584),
                            SectionId = 1,
                            UpdatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5581),
                            Url = "/image/index/bg1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5586),
                            SectionId = 3,
                            UpdatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5585),
                            Url = "/image/Information/ceo.jpg"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5588),
                            Name = "Image 1",
                            SectionId = 4,
                            UpdatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5587),
                            Url = "/image/Information/vision1.jpg"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5590),
                            Name = "Image 2",
                            SectionId = 4,
                            UpdatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5589),
                            Url = "/image/Information/vision2.jpg"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5592),
                            SectionId = 5,
                            UpdatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5591),
                            Url = "/image/Information/history.jpg"
                        });
                });

            modelBuilder.Entity("Core.Models.Entity.LeaderShip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("LeaderShip", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5612),
                            ImageUrl = "/image/Information/ceo1.jpg",
                            Name = "MR NGUYỄN TRÍ ĐĂNG",
                            Position = "TRỢ LÝ TỔNG GIÁM ĐỐC",
                            UpdatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5610)
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5614),
                            ImageUrl = "/image/Information/ceo2.jpg",
                            Name = "MR NGUYỄN TRÍ ĐĂNG",
                            Position = "TRỢ LÝ TỔNG GIÁM ĐỐC",
                            UpdatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5613)
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5616),
                            ImageUrl = "/image/Information/ceo3.jpg",
                            Name = "MR NGUYỄN TRÍ ĐĂNG",
                            Position = "TRỢ LÝ TỔNG GIÁM ĐỐC",
                            UpdatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5615)
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5619),
                            ImageUrl = "/image/Information/ceo4.jpg",
                            Name = "MR NGUYỄN TRÍ ĐĂNG",
                            Position = "TRỢ LÝ TỔNG GIÁM ĐỐC",
                            UpdatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5618)
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5621),
                            ImageUrl = "/image/Information/ceo5.jpg",
                            Name = "MR NGUYỄN TRÍ ĐĂNG",
                            Position = "TRỢ LÝ TỔNG GIÁM ĐỐC",
                            UpdatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5620)
                        });
                });

            modelBuilder.Entity("Core.Models.Entity.Page", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Page", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5315),
                            Name = "Home",
                            UpdatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5309),
                            Url = "/"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5317),
                            Name = "Introduction",
                            UpdatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5316),
                            Url = "/introduction"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5320),
                            Name = "Product",
                            UpdatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5319),
                            Url = "/product"
                        });
                });

            modelBuilder.Entity("Core.Models.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("Core.Models.Entity.ProductDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Specifications")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductDetail", (string)null);
                });

            modelBuilder.Entity("Core.Models.Entity.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ButtonUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("PageId")
                        .HasColumnType("int");

                    b.Property<int?>("SectionParentId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PageId");

                    b.HasIndex("SectionParentId");

                    b.ToTable("Section", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5497),
                            Name = "Home",
                            PageId = 1,
                            UpdatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5495)
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5499),
                            Name = "Introduction",
                            PageId = 2,
                            UpdatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5498)
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5501),
                            Name = "About",
                            SectionParentId = 2,
                            UpdatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5500)
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5504),
                            Name = "Vision",
                            SectionParentId = 2,
                            UpdatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5503)
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5505),
                            Name = "History",
                            SectionParentId = 2,
                            UpdatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5505)
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5507),
                            Name = "Leadership",
                            SectionParentId = 2,
                            UpdatedDate = new DateTime(2024, 4, 3, 18, 34, 49, 91, DateTimeKind.Local).AddTicks(5506)
                        });
                });

            modelBuilder.Entity("Core.Models.Entity.Describe", b =>
                {
                    b.HasOne("Core.Models.Entity.Section", "Section")
                        .WithMany("Describes")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Core.Models.Entity.Image", b =>
                {
                    b.HasOne("Core.Models.Entity.Section", "Section")
                        .WithMany("Images")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Core.Models.Entity.ProductDetail", b =>
                {
                    b.HasOne("Core.Models.Entity.Product", "Product")
                        .WithMany("ProductDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Core.Models.Entity.Section", b =>
                {
                    b.HasOne("Core.Models.Entity.Page", "Page")
                        .WithMany("Sections")
                        .HasForeignKey("PageId");

                    b.HasOne("Core.Models.Entity.Section", "SectionParent")
                        .WithMany("Sections")
                        .HasForeignKey("SectionParentId");

                    b.Navigation("Page");

                    b.Navigation("SectionParent");
                });

            modelBuilder.Entity("Core.Models.Entity.Page", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Core.Models.Entity.Product", b =>
                {
                    b.Navigation("ProductDetails");
                });

            modelBuilder.Entity("Core.Models.Entity.Section", b =>
                {
                    b.Navigation("Describes");

                    b.Navigation("Images");

                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
