// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MBAContext))]
    [Migration("20240508055411_AdminCreate")]
    partial class AdminCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Models.Entity.Describe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("Describe", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2060),
                            Description = "VỀ CÔNG TY",
                            Name = "Big Title",
                            SectionId = 3,
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2055)
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2064),
                            Description = "Tổng Giám đốc - Người sáng lập MBA",
                            Name = "General Manager",
                            SectionId = 3,
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2063)
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2067),
                            Description = "Let’s Grow Together!\r\nCùng đến thành công!",
                            Name = "Slogan",
                            SectionId = 3,
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2066)
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2070),
                            Description = "MBA International JSC",
                            Name = "Tag",
                            SectionId = 3,
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2068)
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2072),
                            Description = "CÔNG TY CỔ PHẦN QUỐC TẾ MBA",
                            Name = "Title",
                            SectionId = 3,
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2071)
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2075),
                            Description = "Công ty CP Quốc tế MBA là nhà sản xuất và phân phối hàng đầu các giải pháp toàn diện cho ngành Giáo Dục – Y Tế - Công Nghệ Cao. Với hơn 17 năm kinh nghiệm, MBA tự hào với đội ngũ nhân viên giàu kinh nghiệm, nhiệt huyết và chuyên nghiệp, luôn mang đến cho khách hàng những trải nghiệm tốt nhất về sản phẩm và dịch vụ chính hãng. Với  xu hướng phát triển không ngừng của ngành khoa học thông tin và cách mạng công nghiệp 4.0, nhằm đáp ứng nhu cầu ngày càng cao của khách hàng trong việc trang bị các thiết bị điện tử và các giải pháp công nghệ, Công Ty Cổ Phần Quốc Tế MBA đã mang đến cho Quý khách hàng những sản phẩm hiện đại nhất của các hãng nổi tiếng trên thị trường Bên cạnh đó ngoài chức năng phân phối, MBA cũng là đại diện bảo hành, bảo trì, sữa chữa và thực hiện các dịch vụ sau bán hàng của các đối tác nói trên nhằm cung cấp giải pháp toàn diện, hiệu quả cho khách hàng khi sử dụng sản phẩm MBA phân phối với đội kỹ thuật viên giàu kinh nghiệm, linh kiện thay thế chính hãng và giá cả hợp lý.",
                            Name = "Detail",
                            SectionId = 3,
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2073)
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2114),
                            Description = "TẦM NHÌN - SỨ MỆNH",
                            Name = "Big Title",
                            SectionId = 4,
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2113)
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2116),
                            Description = "Tầm nhìn thương hiệu",
                            Name = "Title",
                            SectionId = 4,
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2115)
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2119),
                            Description = "MBA International Corporation luôn hướng tới mục tiêu duy trì vị trí thương hiệu hàng đầu tại Việt Nam trong lĩnh vực phân phối các Thiết bị Giáo dục – Y tế – Công nghệ cao.",
                            Name = "Detail",
                            SectionId = 4,
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2118)
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2121),
                            Description = "Sứ mệnh",
                            Name = "Title2",
                            SectionId = 4,
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2120)
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2123),
                            Description = "Với tôn chỉ \" Let's Grow Together! - Cùng đến thành công !\", Công ty CP Quốc Tế MBA luôn hướng tới sự phát triển bền vững không chỉ cho doanh nghiệp mà còn cho cộng đồng bằng cam kết mang những sản phẩm ngành Giáo Dục - Y Tế - Công Nghệ Cao chất lượng hàng đầu Thế giới với giá cả cạnh tranh nhất đến đông đảo Quý khách hàng.",
                            Name = "Title2",
                            SectionId = 4,
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2122)
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2126),
                            Description = "LỊCH SỬ HÌNH THÀNH",
                            Name = "Big Title",
                            SectionId = 5,
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2124)
                        },
                        new
                        {
                            Id = 13,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2130),
                            Description = "BAN LÃNH ĐẠO",
                            Name = "Big Title",
                            SectionId = 6,
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2127)
                        });
                });

            modelBuilder.Entity("Core.Models.Entity.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("Image", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2169),
                            SectionId = 1,
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2166),
                            Url = "/image/index/bg1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2172),
                            SectionId = 3,
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2171),
                            Url = "/image/Information/ceo.jpg"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2175),
                            Name = "Image 1",
                            SectionId = 4,
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2173),
                            Url = "/image/Information/vision1.jpg"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2177),
                            Name = "Image 2",
                            SectionId = 4,
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2176),
                            Url = "/image/Information/vision2.jpg"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2179),
                            SectionId = 5,
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2178),
                            Url = "/image/Information/history.jpg"
                        });
                });

            modelBuilder.Entity("Core.Models.Entity.LeaderShip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("LeaderShip", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2219),
                            ImageUrl = "/image/Information/ceo1.jpg",
                            Name = "MR NGUYỄN TRÍ ĐĂNG",
                            Position = "TRỢ LÝ TỔNG GIÁM ĐỐC",
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2217)
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2223),
                            ImageUrl = "/image/Information/ceo2.jpg",
                            Name = "MR NGUYỄN TRÍ ĐĂNG",
                            Position = "TRỢ LÝ TỔNG GIÁM ĐỐC",
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2221)
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2225),
                            ImageUrl = "/image/Information/ceo3.jpg",
                            Name = "MR NGUYỄN TRÍ ĐĂNG",
                            Position = "TRỢ LÝ TỔNG GIÁM ĐỐC",
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2224)
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2227),
                            ImageUrl = "/image/Information/ceo4.jpg",
                            Name = "MR NGUYỄN TRÍ ĐĂNG",
                            Position = "TRỢ LÝ TỔNG GIÁM ĐỐC",
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2226)
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2231),
                            ImageUrl = "/image/Information/ceo5.jpg",
                            Name = "MR NGUYỄN TRÍ ĐĂNG",
                            Position = "TRỢ LÝ TỔNG GIÁM ĐỐC",
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2229)
                        });
                });

            modelBuilder.Entity("Core.Models.Entity.Page", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Page", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(1842),
                            Name = "Home",
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(1836),
                            Url = "/"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(1845),
                            Name = "Introduction",
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(1844),
                            Url = "/introduction"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(1847),
                            Name = "Product",
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(1846),
                            Url = "/product"
                        });
                });

            modelBuilder.Entity("Core.Models.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2438),
                            ImageUrl = "/image/Product/product1.jpg",
                            Name = "CÔNG NGHỆ CAO",
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2435)
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2442),
                            ImageUrl = "/image/Product/product2.jpg",
                            Name = "THIẾT BỊ Y TẾ",
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2441)
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2444),
                            ImageUrl = "/image/Product/product3.jpg",
                            Name = "THIẾT BỊ GIÁO DỤC",
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2443)
                        });
                });

            modelBuilder.Entity("Core.Models.Entity.ProductDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Specifications")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductDetail", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "167",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2479),
                            ImageUrl = "/image/Product/moredetail/product1.jpg",
                            Name = "CÔNG NGHỆ THÔNG TIN",
                            ProductId = 1,
                            Status = "Còn Hàng",
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2472)
                        },
                        new
                        {
                            Id = 2,
                            Code = "166",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2484),
                            ImageUrl = "/image/Product/moredetail/product2.jpg",
                            Name = "CÔNG NGHỆ SINH HỌC",
                            ProductId = 1,
                            Status = "Còn Hàng",
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2481)
                        },
                        new
                        {
                            Id = 3,
                            Code = "166",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2487),
                            ImageUrl = "/image/Product/moredetail/product3.jpg",
                            Name = "CÔNG NGHỆ VẬT LIỆU MỚI",
                            ProductId = 1,
                            Status = "Còn Hàng",
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2485)
                        },
                        new
                        {
                            Id = 4,
                            Code = "166",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2490),
                            ImageUrl = "/image/Product/moredetail/product4.jpg",
                            Name = "CÔNG NGHỆ TỰ ĐỘNG HOÁ",
                            ProductId = 1,
                            Status = "Còn Hàng",
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2488)
                        },
                        new
                        {
                            Id = 5,
                            Code = "166",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2492),
                            ImageUrl = "/image/Product/moredetail/product4.jpg",
                            Name = "HỆ THỐNG PHÒNG TAI MŨI HỌNG",
                            ProductId = 2,
                            Status = "Còn Hàng",
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2491)
                        },
                        new
                        {
                            Id = 6,
                            Code = "166",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2496),
                            ImageUrl = "/image/Product/moredetail/product4.jpg",
                            Name = "HỆ THỐNG PHÒNG CHUẨN ĐOÁN",
                            ProductId = 2,
                            Status = "Còn Hàng",
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2494)
                        },
                        new
                        {
                            Id = 7,
                            Code = "166",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2499),
                            ImageUrl = "/image/Product/moredetail/product4.jpg",
                            Name = "HỆ THỐNG PHÒNG CHỤP CT",
                            ProductId = 2,
                            Status = "Còn Hàng",
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2497)
                        },
                        new
                        {
                            Id = 8,
                            Code = "166",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2502),
                            ImageUrl = "/image/Product/moredetail/product4.jpg",
                            Name = "HỆ THỐNG PHÒNG CHỤP PHẪU THUẬT",
                            ProductId = 2,
                            Status = "Còn Hàng",
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2500)
                        },
                        new
                        {
                            Id = 9,
                            Code = "166",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2504),
                            ImageUrl = "/image/Product/moredetail/product4.jpg",
                            Name = "PHÒNG HỌC BỘ MÔN HOÁ",
                            ProductId = 3,
                            Status = "Còn Hàng",
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2503)
                        },
                        new
                        {
                            Id = 10,
                            Code = "166",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2507),
                            ImageUrl = "/image/Product/moredetail/product4.jpg",
                            Name = "PHÒNG HỌC BỘ MÔN LÝ",
                            ProductId = 3,
                            Status = "Còn Hàng",
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2506)
                        },
                        new
                        {
                            Id = 11,
                            Code = "166",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2510),
                            ImageUrl = "/image/Product/moredetail/product4.jpg",
                            Name = "PHÒNG HỌC TIN HỌC",
                            ProductId = 3,
                            Status = "Còn Hàng",
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2509)
                        },
                        new
                        {
                            Id = 12,
                            Code = "166",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2513),
                            ImageUrl = "/image/Product/moredetail/product4.jpg",
                            Name = "PHÒNG HỌC BỘ MÔN SINH",
                            ProductId = 3,
                            Status = "Còn Hàng",
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2512)
                        });
                });

            modelBuilder.Entity("Core.Models.Entity.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ButtonUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("PageId")
                        .HasColumnType("int");

                    b.Property<int?>("SectionParentId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PageId");

                    b.HasIndex("SectionParentId");

                    b.ToTable("Section", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(1990),
                            Name = "Home",
                            PageId = 1,
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(1986)
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(1992),
                            Name = "Introduction",
                            PageId = 2,
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(1991)
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(1998),
                            Name = "About",
                            SectionParentId = 2,
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(1995)
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2001),
                            Name = "Vision",
                            SectionParentId = 2,
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(1999)
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2003),
                            Name = "History",
                            SectionParentId = 2,
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2002)
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2006),
                            Name = "Leadership",
                            SectionParentId = 2,
                            UpdatedDate = new DateTime(2024, 5, 8, 12, 54, 10, 120, DateTimeKind.Local).AddTicks(2004)
                        });
                });

            modelBuilder.Entity("Core.Models.Entity.Describe", b =>
                {
                    b.HasOne("Core.Models.Entity.Section", "Section")
                        .WithMany("Describes")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Core.Models.Entity.Image", b =>
                {
                    b.HasOne("Core.Models.Entity.Section", "Section")
                        .WithMany("Images")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Core.Models.Entity.ProductDetail", b =>
                {
                    b.HasOne("Core.Models.Entity.Product", "Product")
                        .WithMany("ProductDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Core.Models.Entity.Section", b =>
                {
                    b.HasOne("Core.Models.Entity.Page", "Page")
                        .WithMany("Sections")
                        .HasForeignKey("PageId");

                    b.HasOne("Core.Models.Entity.Section", "SectionParent")
                        .WithMany("Sections")
                        .HasForeignKey("SectionParentId");

                    b.Navigation("Page");

                    b.Navigation("SectionParent");
                });

            modelBuilder.Entity("Core.Models.Entity.Page", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Core.Models.Entity.Product", b =>
                {
                    b.Navigation("ProductDetails");
                });

            modelBuilder.Entity("Core.Models.Entity.Section", b =>
                {
                    b.Navigation("Describes");

                    b.Navigation("Images");

                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
